# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtrackr
spring.datasource.username=jobtrackr_user
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8080
app.jwt.secret=your-super-secret-jwt-key-make-this-long-and-random
app.jwt.expiration=86400000
app.cors.allowed-origins=http://localhost:3000

anthropic.api.key=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
groq.api.key=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